(()=>{"use strict";
const tools=[
["nmap","Network discovery and service enumeration"],["masscan","Fast port discovery"],["rustscan","Fast port scanner"],["amass","Attack-surface discovery"],["sublist3r","Subdomain enumeration"],["theharvester","OSINT collection"],["recon-ng","Recon framework"],["gobuster","Directory and DNS enumeration"],["ffuf","Web fuzzing"],["nikto","Web server checks"],["whatweb","Web technology fingerprinting"],["httpx","HTTP probing"],["nuclei","Template-based security checks"],["owasp-zap","Web security proxy"],["burp-suite","Web security testing proxy"],["metasploit","Security testing framework"],["sqlmap","SQL injection testing"],["hydra","Credential auditing"],["hashcat","Password recovery/auditing"],["john","Password auditing"],["wireshark","Packet analysis"],["tshark","CLI packet analysis"],["netcat","Network connection utility"],["sslscan","TLS configuration inspection"],["enum4linux","SMB enumeration"],["impacket","Network protocol tooling"],["responder","Network authentication lab"],["shodan","Internet exposure research"],["whois","Domain registration lookup"],["dig","DNS query utility"],["nslookup","DNS query utility"],["searchsploit","Exploit reference search"],["ping","Connectivity check"],["traceroute","Route inspection"],["curl","HTTP request testing"],["wget","HTTP retrieval"],["git","Version control"],["python","Python interpreter"],["linux","Linux command practice"],["dvwa","Vulnerable web lab"],["juice-shop","OWASP Juice Shop lab"],["webgoat","WebGoat training lab"],["kioptrix","Vulnerable VM training lab"],["chmod","Linux permissions practice"],["grep","Text search"],["find","Filesystem search"],["ss","Socket inspection"],["ip","Network interface inspection"],["dig+trace","DNS delegation trace"],["base64","Encoding/decoding practice"],["openssl","Cryptography/TLS CLI"]];

function open(){let old=document.getElementById("toolConsole");if(old){old.classList.add("open");return}
const modal=document.createElement("div");modal.id="toolConsole";modal.className="lab-modal open";modal.innerHTML='<div class="lab-modal-backdrop"></div><div class="lab-modal-sheet"><div class="lab-modal-head"><div><span class="lab-kicker">AUTHORIZED LAB / SIMULATION</span><h2>ETHICAL TOOL TERMINAL</h2></div><button class="lab-close" aria-label="Close">×</button></div><div class="tool-layout"><aside class="tool-list"><input id="toolFilter" placeholder="Filter tools...">'+tools.map((t,i)=>'<button data-tool="'+i+'"><b>'+t[0]+'</b><small>'+t[1]+'</small></button>').join("")+'</aside><section class="terminal-box"><div class="terminal-head"><span>LAB@CYBER:~$</span><span id="toolMode">SIMULATED</span></div><div id="terminalOutput" class="terminal-output"></div><form id="terminalForm" class="terminal-form"><span>$</span><input id="terminalInput" autocomplete="off" spellcheck="false" placeholder="type help or select a tool"><button>RUN</button></form><div class="terminal-note">Browser-safe simulation. No packets, scans, passwords or external targets are touched.</div></section></div></div>';
document.body.appendChild(modal);
const out=modal.querySelector("#terminalOutput"),input=modal.querySelector("#terminalInput");
function print(s){out.innerHTML+=s+"\n";out.scrollTop=out.scrollHeight}
function run(name,args){const target=args||"127.0.0.1";const desc=tools.find(t=>t[0]===name)?.[1]||"lab command";print('<span class="t-cmd">$ '+name+' '+target+'</span>');print('<span class="t-dim">[SIMULATION] '+desc+'</span>');if(["nmap","masscan","rustscan"].includes(name))print("PORT     STATE     SERVICE\n22/tcp   open      ssh\n80/tcp   open      http\n443/tcp  open      https\n<span class="t-ok">No real network traffic was generated.</span>");else if(["gobuster","ffuf"].includes(name))print("/admin   [200]\n/assets  [301]\n/index   [200]\n<span class="t-ok">Synthetic lab response only.</span>");else if(["whois","dig","nslookup","dig+trace"].includes(name))print("domain: example.lab\nstatus: TEST DATA\n<span class="t-ok">No live DNS lookup performed.</span>");else if(name==="ping")print("64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.031 ms\n<span class="t-ok">Loopback simulation.</span>");else print("Output: '+name+' completed in the educational sandbox.\n<span class="t-ok">SAFE / SIMULATED</span>");}
function command(v){const p=v.trim().split(/\s+/),n=p.shift()?.toLowerCase();if(!n)return;if(n==="clear"){out.innerHTML="";return}if(n==="help"){print("help  list  run <tool> [target]  clear  exit");return}if(n==="list"){print(tools.map(t=>t[0]).join("  "));return}if(n==="exit"){modal.classList.remove("open");return}if(tools.some(t=>t[0]===n)){run(n,p.join(" ")||"127.0.0.1");return}if(n==="run"&&tools.some(t=>t[0]===p[0])){const x=p.shift();run(x,p.join(" ")||"127.0.0.1");return}print('<span class="t-warn">command not found. Type help.</span>')}
function select(i){const t=tools[i];input.value="run "+t[0];input.focus();print('<span class="t-cmd">$ run '+t[0]+' 127.0.0.1</span>');run(t[0],"127.0.0.1")}
modal.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>select(+b.dataset.tool));
modal.querySelector("#toolFilter").oninput=e=>{const q=e.target.value.toLowerCase();modal.querySelectorAll("[data-tool]").forEach(b=>b.hidden=!b.innerText.toLowerCase().includes(q))};
modal.querySelector(".lab-close").onclick=()=>modal.classList.remove("open");modal.querySelector(".lab-modal-backdrop").onclick=()=>modal.classList.remove("open");
modal.querySelector("#terminalForm").onsubmit=e=>{e.preventDefault();command(input.value);input.value=""};print("CYBER SYSTEMS LAB TERMINAL\nType help to begin. All outputs are simulated.");input.focus()}
window.CyberLabTerminal={open,tools};
})();