window.CYBER_TREE={id:"lab",name:"CYBER SYSTEMS LAB",type:"root",category:"blue",description:"A connected map of engineering, software, data, cybersecurity, projects and learning.",children:[
{id:"about",name:"ABOUT",type:"branch",category:"blue",description:"The ideas, disciplines and working principles behind the lab.",children:[
{id:"profile",name:"PROFILE",category:"blue",description:"A concise professional profile focused on building practical systems across engineering, software and cybersecurity.",content:["The public identity is intentionally compact. The deeper story is the connection between physical systems, software, data and security."],tags:["engineering","software","cybersecurity","systems"]},
{id:"engineering",name:"ENGINEERING",category:"green",description:"Hands-on engineering shaped a preference for precision, troubleshooting, safety and systems thinking.",content:["Experience with electronic and industrial systems provides the physical-world foundation behind the digital work."],tags:["electronics","automation","systems","safety"]},
{id:"cybersecurity",name:"CYBERSECURITY",category:"orange",description:"Security learning and practical experimentation across networks, web applications, Linux and ethical testing.",content:["The lab treats cybersecurity as disciplined problem solving: understand the system, identify weaknesses, validate safely and document what was learned."],tags:["network security","web security","ethical testing","Linux"]},
{id:"data",name:"DATA",category:"purple",description:"Data analysis connects programming with evidence, helping turn raw information into useful decisions.",content:["The data track includes Python, Pandas, BigQuery, visualization and introductory machine learning."],tags:["Python","Pandas","BigQuery","machine learning"]},
{id:"philosophy",name:"PHILOSOPHY",category:"blue",description:"Privacy-conscious, human-centered technology with ethics treated as part of the engineering process.",content:["The working principle is simple: build useful things, understand their consequences and avoid treating security or privacy as an afterthought."],tags:["privacy","ethics","accessibility","responsibility"]}
]},
{id:"work",name:"WORK",type:"branch",category:"green",description:"The practical systems and disciplines that inform the lab.",children:[
{id:"electronics",name:"ELECTRONICS",category:"green",description:"Electronic systems, troubleshooting and installation work.",content:["The engineering background provides a practical understanding of components, signals, diagnostics and real-world constraints."],tags:["electronics","diagnostics","installation"]},
{id:"aviation",name:"AVIATION SYSTEMS",category:"green",description:"Exposure to safety-oriented electronic and aviation-related systems.",content:["This branch represents the systems mindset developed through aviation and industrial engineering environments."],tags:["aviation","systems","safety"]},
{id:"webdev",name:"WEB DEVELOPMENT",category:"blue",description:"Static and interactive web development with a strong focus on usability, accessibility and secure coding.",content:["Core technologies include HTML, CSS, JavaScript and Python, with attention to responsive interfaces and security-aware implementation."],tags:["HTML","CSS","JavaScript","Python","secure coding"]},
{id:"research",name:"RESEARCH / FREELANCE",category:"purple",description:"Independent experiments, security research, learning projects and practical prototypes.",content:["This is the experimental layer of the lab: ideas are tested, documented and iterated rather than presented as finished products before they are ready."],tags:["research","prototyping","experimentation"]}
]},
{id:"lab",name:"LAB",type:"branch",category:"orange",description:"Interactive security tooling and controlled learning environments.",children:[
{id:"recon",name:"RECON",category:"orange",description:"Reconnaissance tools for authorized security assessment and learning.",content:["Includes tools such as Nmap, Masscan, Rustscan, Amass, Sublist3r, theHarvester and Recon-ng."],tags:["Nmap","Masscan","Amass","Recon-ng"],ethics:"Use reconnaissance tools only against systems you own or have explicit permission to assess."},
{id:"websecurity",name:"WEB SECURITY",category:"orange",description:"Tools and references for understanding web attack surfaces.",content:["Includes Gobuster, ffuf, Nikto, WhatWeb, httpx, Nuclei, OWASP ZAP and Burp Suite."],tags:["Gobuster","ffuf","Nikto","Nuclei","OWASP ZAP"],ethics:"Testing must remain within an authorized scope."},
{id:"sectesting",name:"SECURITY TESTING",category:"orange",description:"Controlled exploitation and credential-security tooling for lab environments.",content:["Includes Metasploit, SQLmap, Hydra, Hashcat and John the Ripper as learning tools."],tags:["Metasploit","SQLmap","Hydra","Hashcat"],ethics:"These tools can cause real impact. Use deliberately in labs, CTFs or systems where testing is authorized."},
{id:"networkosint",name:"NETWORK / OSINT",category:"orange",description:"Network inspection and open-source intelligence techniques.",content:["Includes Wireshark, TShark, Netcat, SSLScan, DNS and WHOIS utilities, Shodan, SearchSploit, enum4linux and related tools."],tags:["Wireshark","TShark","OSINT","DNS","WHOIS"],ethics:"Public information is not automatically permission to target a person or system."},
{id:"traininglabs",name:"TRAINING LABS",category:"purple",description:"Intentionally vulnerable environments used for hands-on learning.",content:["The learning set includes DVWA, OWASP Juice Shop, WebGoat and Kioptrix-style practice environments."],tags:["DVWA","OWASP Juice Shop","WebGoat","Kali"]},
{id:"terminal",name:"BROWSER TERMINAL",category:"orange",description:"A safe browser-based interface for exploring the toolkit without pretending that GitHub Pages can execute local security commands.",content:["The browser interface is educational and simulated. Real local commands belong in the Kali/WSL2 toolkit included in the project repository."],tags:["terminal","simulation","Kali","WSL2"]}
]},
{id:"projects",name:"PROJECTS",type:"branch",category:"purple",description:"Selected builds showing how the disciplines connect.",children:[
{id:"pentestproject",name:"PENTEST TOOLKIT",category:"orange",description:"A local Kali/WSL2 Bash toolkit organizing a broad set of authorized security-learning utilities.",content:["The project groups reconnaissance, web security, network inspection, OSINT, development and training labs into one interactive workflow."],tags:["Bash","Kali","WSL2","security tooling"]},
{id:"dataproject",name:"DATA ANALYTICS",category:"purple",description:"Python and cloud-data experiments turning datasets into analysis workflows.",content:["The data work includes Pandas, BigQuery, visualization and machine-learning experimentation."],tags:["Python","Pandas","BigQuery","ML"]},
{id:"secureweb",name:"SECURE WEB",category:"blue",description:"Web-development experiments where security, accessibility and responsive design are considered together.",content:["The goal is not just a working interface, but an interface that respects users, validates inputs and reduces avoidable security exposure."],tags:["JavaScript","HTML5","CSS3","security"]},
{id:"systemsmonitor",name:"SYSTEMS MONITOR",category:"green",description:"A systems-oriented concept connecting physical signals, automation, data and dashboards.",content:["This project represents the bridge between engineering systems and software observability."],tags:["Python","IoT","electronics","dashboard"]},
{id:"securityblog",name:"SECURITY BLOG",category:"purple",description:"Educational writing about cybersecurity, technology and responsible learning.",content:["The blog is part of the knowledge layer: explain difficult concepts simply, document lessons and keep the learning trail public."],tags:["writing","education","cybersecurity"]}
]},
{id:"knowledge",name:"KNOWLEDGE",type:"branch",category:"purple",description:"Study notes, references and practical learning paths.",children:[
{id:"fundamentals",name:"FUNDAMENTALS",category:"blue",description:"Networking, operating systems, security concepts and core technical foundations.",content:["Topics include networking models, protocols, ports, Linux concepts, risk management and security fundamentals."],tags:["networking","Linux","security fundamentals"]},
{id:"learninghub",name:"LEARNING HUB",category:"purple",description:"External learning resources used for structured cybersecurity practice.",content:["PortSwigger Web Security Academy, OWASP Cheat Sheets and Hack The Box are among the external resources connected to the lab."],tags:["PortSwigger","OWASP","Hack The Box"],links:[{label:"PortSwigger Web Security Academy",url:"https://portswigger.net/web-security"},{label:"OWASP Cheat Sheets",url:"https://cheatsheetseries.owasp.org/"},{label:"Hack The Box",url:"https://www.hackthebox.com/"}]},
{id:"datalearning",name:"DATA LEARNING",category:"purple",description:"Python, SQL, cloud analytics and machine-learning practice.",content:["Learning projects focus on moving from raw datasets through cleaning, exploration, modeling and interpretation."],tags:["Python","SQL","Pandas","machine learning"]},
{id:"quizzes",name:"QUIZZES / GAMES",category:"blue",description:"Small interactive exercises used to reinforce technical fundamentals.",content:["The original site includes Linux, Security+ ports and OSI quizzes alongside simple browser games."],tags:["OSI","ports","Linux","JavaScript"]},
{id:"studynotes",name:"STUDY NOTES",category:"purple",description:"Long-form learning notes that document the transition into cybersecurity and related technical fields.",content:["Notes are written as a learning trail rather than as claims of mastery."],tags:["GitBook","notes","learning"]}
]},
{id:"contact",name:"CONTACT",type:"branch",category:"red",description:"Public channels for professional work, projects and writing.",children:[
{id:"github",name:"GITHUB",category:"red",description:"Code, experiments and public repositories.",tags:["repositories","code"],links:[{label:"Open GitHub profile",url:"https://github.com/HephzibahBehulah"}]},
{id:"linkedin",name:"LINKEDIN",category:"red",description:"Professional profile and career-facing presence.",tags:["professional"],links:[{label:"Open LinkedIn profile",url:"https://www.linkedin.com/in/isaac-adigun/"}]},
{id:"blog",name:"BLOG",category:"red",description:"Cybersecurity and technology writing.",tags:["articles","education"],links:[{label:"Open blog",url:"https://hephzibahbehulah.blogspot.com/"}]},
{id:"gitbook",name:"GITBOOK",category:"red",description:"Long-form technical notes and learning documentation.",tags:["documentation","learning"],links:[{label:"Open GitBook",url:"https://app.gitbook.com/"}]},
{id:"email",name:"EMAIL",category:"red",description:"Direct professional contact.",content:["For privacy, the email address is intentionally not embedded in the public tree data. Add a dedicated contact address here only when you want it exposed publicly."],tags:["contact","privacy"]},
{id:"identity",name:"PUBLIC IDENTITY",category:"red",description:"The public-facing identity used across the lab.",content:["Hephzibah Behulah is the public identity used for this project. The site deliberately keeps personal details minimal and focuses on work, systems and ideas."],tags:["identity","privacy"]}
]}
]};