window.CYBER_TREE={id:"lab",name:"CYBER SYSTEMS LAB",type:"root",category:"blue",description:"An interactive map connecting engineering, cybersecurity, web development, data, projects, learning and public resources.",children:[
{id:"about",name:"ABOUT",type:"branch",category:"blue",description:"Who I am, what I study and the systems thinking behind the work.",children:[
{id:"profile",name:"PROFILE",category:"blue",description:"Ephzibah Behulah",content:["Isaac Oluwole Adigun","Elektroniker | Cybersecurity Student | Web Developer","Cybersecurity student, web developer and data enthusiast with an engineering foundation. The public profile keeps personal details focused on work, learning and ideas."],tags:["Ephzibah Behulah","Isaac Oluwole Adigun","Cybersecurity","Web Developer","Elektroniker"]},
{id:"timeline",name:"TIMELINE",category:"blue",description:"Professional and learning milestones.",content:["2023 - Present — Elektroniker @ Centerline Design, Hamburg","Specializing in Airbus systems and lighting installations.","2022 - 2026 — BSc Cybersecurity @ IU Internationale Hochschule","Focus on network security, ethical hacking and cryptography.","2023 — Data Analytics @ ReDI School Hamburg","Python, Pandas and BigQuery training."],tags:["Centerline Design","Airbus","IU","ReDI School","Hamburg"]},
{id:"engineering",name:"ENGINEERING",category:"green",description:"Hands-on engineering shaped a preference for precision, troubleshooting, safety and systems thinking.",content:["Full-time Elektroniker work at Centerline Design includes Airbus systems and lighting installations."],tags:["electronics","aviation","lighting","systems"],links:[{label:"Centerline Design",url:"https://centerlinedesign.de/de/"}]},
{id:"cybersecurity",name:"CYBERSECURITY",category:"orange",description:"Security learning across networks, web applications, Linux, ethical hacking and cryptography.",content:["The lab treats security as disciplined problem solving: understand the system, identify weaknesses, validate safely and document what was learned."],tags:["network security","ethical hacking","cryptography","Linux"]},
{id:"data",name:"DATA",category:"purple",description:"Data analytics connecting programming with evidence.",content:["Training includes Python, Pandas and BigQuery. Projects explore cleaning, analysis, visualization and machine learning."],tags:["Python","Pandas","BigQuery","analytics"]},
{id:"philosophy",name:"PHILOSOPHY",category:"blue",description:"Secure, accessible and human-centered technology.",content:["When I am not debugging code or studying security protocols, I explore ethical AI applications and aviation technology.","My mission is to build secure, accessible digital systems that empower users while protecting their data.","Passion: secure web design and ethical AI."],tags:["privacy","ethics","ethical AI","accessibility"]}
]},
{id:"work",name:"WORK",type:"branch",category:"green",description:"Professional skills and disciplines.",children:[
{id:"electronics",name:"ELEKTRONIKER",category:"green",description:"Electronics, installation, troubleshooting and practical systems work.",content:["Hands-on engineering experience provides a physical-world foundation for digital systems thinking."],tags:["Elektroniker","electronics","diagnostics","installation"]},
{id:"aviation",name:"AVIATION SYSTEMS",category:"green",description:"Aviation-related electronic systems and safety-oriented environments.",content:["Engineering experience includes work around Airbus systems and lighting installations."],tags:["Airbus","aviation","lighting","safety"]},
{id:"webdev",name:"WEB DEVELOPMENT",category:"blue",description:"Responsive, accessible and security-aware web development.",content:["HTML5, CSS3, JavaScript, Tailwind CSS and secure web practices are part of the web-development track."],tags:["HTML5","CSS3","JavaScript","Tailwind","secure coding"]},
{id:"datawork",name:"DATA ANALYTICS",category:"purple",description:"Data analysis and cloud analytics.",content:["Python, Pandas, Google Colab and BigQuery support data-learning and analysis work."],tags:["Python","Pandas","Google Colab","BigQuery"]},
{id:"research",name:"RESEARCH / FREELANCE",category:"purple",description:"Independent experiments, security research and practical prototypes.",content:["Ideas are tested, documented and iterated as learning projects."],tags:["research","prototyping","experimentation"]},
{id:"skills",name:"TECH & TOOLS",category:"blue",description:"Technology stack used across the site and projects.",content:["HTML5 | CSS3 | JavaScript | Tailwind CSS | Figma | GitHub | Python | cPanel | Namecheap | Google Colab | BigQuery | Netlify | Lighthouse | SEO | Git Sync | Agile | Scrum"],tags:["HTML5","CSS3","JavaScript","Figma","GitHub","Python","SEO","Agile","Scrum"]}
]},
{id:"lab",name:"LAB",type:"branch",category:"orange",description:"Interactive, browser-safe security learning tools.",children:[
{id:"recon",name:"RECON",category:"orange",description:"Authorized reconnaissance tools.",content:["Nmap, Masscan, Rustscan, Amass, Sublist3r, theHarvester and Recon-ng."],tags:["Nmap","Masscan","Rustscan","Amass","Sublist3r","theHarvester","Recon-ng"],ethics:"Use only on systems you own or have explicit permission to assess."},
{id:"websecurity",name:"WEB SECURITY",category:"orange",description:"Web assessment tools.",content:["Gobuster, ffuf, Nikto, WhatWeb, httpx, Nuclei, OWASP ZAP and Burp Suite."],tags:["Gobuster","ffuf","Nikto","WhatWeb","httpx","Nuclei","OWASP ZAP","Burp Suite"],ethics:"Testing must remain within an authorized scope."},
{id:"sectesting",name:"SECURITY TESTING",category:"orange",description:"Controlled security-testing and credential-auditing tools.",content:["Metasploit, SQLmap, Hydra, Hashcat and John the Ripper."],tags:["Metasploit","SQLmap","Hydra","Hashcat","John"],ethics:"Use in owned systems, CTFs, training labs or explicitly permitted assessments."},
{id:"networkosint",name:"NETWORK / OSINT",category:"orange",description:"Network inspection and open-source intelligence.",content:["Wireshark, TShark, Netcat, SSLScan, enum4linux, Impacket, Responder, Shodan, WHOIS, DNS tools and SearchSploit."],tags:["Wireshark","TShark","Netcat","SSLScan","OSINT","Shodan","WHOIS","DNS"],ethics:"Public information is not automatically permission to target a person or system."},
{id:"traininglabs",name:"TRAINING LABS",category:"purple",description:"Intentionally vulnerable environments for hands-on learning.",content:["DVWA, OWASP Juice Shop, WebGoat and Kioptrix-style practice environments."],tags:["DVWA","OWASP Juice Shop","WebGoat","Kioptrix"]},
{id:"terminal",name:"ETHICAL TOOL TERMINAL",category:"orange",description:"A functional browser terminal that provides safe simulated sessions for the ethical hacking toolkit.",content:["Select any tool from the 50+ tool catalogue or type commands such as help, list and run nmap 127.0.0.1.","This interface does not execute real scans from GitHub Pages. It deliberately uses synthetic outputs so visitors can learn the workflow without touching external targets."],tags:["terminal","50+ tools","simulation","Kali","WSL2"]},
{id:"localtoolkit",name:"KALI / WSL2 TOOLKIT",category:"orange",description:"Local command-line toolkit for authorized testing.",content:["The repository also contains a Bash toolkit intended for Kali Linux / WSL2. Real security commands belong in a controlled local environment."],tags:["Bash","Kali","WSL2","pentesting"]}
]},
{id:"projects",name:"PROJECTS",type:"branch",category:"purple",description:"Selected builds and demonstrations.",children:[
{id:"pentestproject",name:"PENTEST TOOLKIT",category:"orange",description:"A local Kali/WSL2 Bash toolkit organizing authorized security-learning utilities.",content:["Reconnaissance, web security, network inspection, OSINT, development and training labs are grouped into one workflow."],tags:["Bash","Kali","WSL2"]},
{id:"dataproject",name:"DATA ANALYTICS",category:"purple",description:"Python and cloud-data experiments.",content:["Data work includes Pandas, BigQuery, visualization and machine-learning experimentation."],tags:["Python","Pandas","BigQuery","ML"],links:[{label:"GitHub profile / repositories",url:"https://github.com/HephzibahBehulah"}]},
{id:"secureweb",name:"SECURE WEB",category:"blue",description:"Web-development experiments combining security, accessibility and responsive design.",content:["The goal is a useful interface that also respects users, validates inputs and reduces avoidable exposure."],tags:["JavaScript","HTML5","CSS3","security"]},
{id:"systemsmonitor",name:"AVIATION / SYSTEMS MONITOR",category:"green",description:"A systems-oriented concept connecting physical signals, automation, data and dashboards.",content:["This represents the bridge between engineering systems and software observability."],tags:["Python","IoT","electronics","dashboard"]},
{id:"securityblog",name:"SECURITY BLOG",category:"purple",description:"Educational writing about cybersecurity and technology.",content:["The blog documents concepts, lessons and responsible learning."],tags:["writing","education","cybersecurity"],links:[{label:"Open blog",url:"https://hephzibahbehulah.blogspot.com/"}]},
{id:"githubrepos",name:"GITHUB REPOS",category:"purple",description:"Public code and project showcase.",content:["Repositories cover web development, cybersecurity, data analytics and learning experiments."],tags:["GitHub","repositories"],links:[{label:"Open GitHub",url:"https://github.com/HephzibahBehulah"}]}
]},
{id:"portfolio",name:"PORTFOLIO",type:"branch",category:"green",description:"The skills that connect the different parts of the lab.",children:[
{id:"portfolio-skills",name:"SKILL MATRIX",category:"green",description:"Core professional and technical areas.",content:["Elektroniker","Cybersecurity","Data Analytics","Aviation Systems","Ethical Hacking","AI-Driven Security","Lighting Design","Web Development","Evangelist"],tags:["Elektroniker","Cybersecurity","Data Analytics","Aviation","Ethical Hacking","AI Security","Lighting","Evangelist"]},
{id:"hosting",name:"HOSTING & DEPLOYMENT",category:"blue",description:"Static web hosting and deployment workflow.",content:["GitHub Pages, Namecheap, cPanel, Netlify, Git Sync and Lighthouse are part of the deployment/tooling knowledge base."],tags:["GitHub Pages","Namecheap","cPanel","Netlify","Lighthouse","SEO"]},
{id:"codecompiler",name:"PYTHON COMPILER",category:"purple",description:"External Python compiler for interactive demonstrations.",content:["Open OneCompiler to run Python examples in its own environment."],tags:["Python","compiler","OneCompiler"],links:[{label:"Open OneCompiler Python",url:"https://onecompiler.com/python"}]}
]},
{id:"knowledge",name:"KNOWLEDGE",type:"branch",category:"purple",description:"Study notes, resources, datasets and interactive learning.",children:[
{id:"fundamentals",name:"FUNDAMENTALS",category:"blue",description:"Networking, Linux, security concepts, ports and risk management.",content:["The learning trail includes networking models, protocols, ports, Linux concepts, risk management and security fundamentals."],tags:["networking","Linux","ports","risk management"]},
{id:"learninghub",name:"CYBER LEARNING",category:"purple",description:"Structured cybersecurity learning resources.",content:["PortSwigger Web Security Academy, OWASP Cheat Sheets and Hack The Box support practical learning."],tags:["PortSwigger","OWASP","Hack The Box"],links:[{label:"PortSwigger Web Security Academy",url:"https://portswigger.net/web-security"},{label:"OWASP Cheat Sheets",url:"https://cheatsheetseries.owasp.org/"},{label:"Hack The Box",url:"https://www.hackthebox.com/"}]},
{id:"datalearning",name:"DATA LEARNING",category:"purple",description:"Python, SQL, cloud analytics and machine-learning practice.",content:["The learning path moves from raw datasets through cleaning, exploration, modeling and interpretation."],tags:["Python","SQL","Pandas","machine learning"],links:[{label:"Kaggle datasets",url:"https://www.kaggle.com/datasets"},{label:"Database Star",url:"https://www.databasestar.com/"}]},
{id:"quizzes",name:"QUIZZES / GAMES",category:"blue",description:"Interactive cybersecurity quiz and simple browser games.",content:["Launch the Cyber Defender Quiz from this node. It covers networking, HTTP, MFA, authentication, OSINT and Linux fundamentals."],tags:["quiz","game","OSI","HTTP","Linux"]},
{id:"resources",name:"RESOURCES",category:"blue",description:"Free books, Bible reading and practical reference resources.",content:["Free eBooks: Open Library and Dummies.com.","Bible Reading: GenZ Bible.","Datasets: Kaggle and Database Star."],tags:["Open Library","Dummies","GenZ Bible","Kaggle"],links:[{label:"Open Library",url:"https://openlibrary.org/"},{label:"Dummies",url:"https://www.dummies.com/"},{label:"GenZ Bible",url:"https://genz.bible/"},{label:"Kaggle datasets",url:"https://www.kaggle.com/datasets"}]},
{id:"studynotes",name:"STUDY NOTES",category:"purple",description:"Long-form notes documenting the transition into cybersecurity and related technical fields.",content:["Notes are written as a learning trail rather than claims of mastery."],tags:["GitBook","notes","learning"],links:[{label:"GitBook",url:"https://app.gitbook.com/invite/8uMbyzwWNsEhLYW0DgiG/6UHlnP4vlkPnzDmzuxw5"}]}
]},
{id:"contact",name:"CONTACT",type:"branch",category:"red",description:"Public channels and direct contact.",children:[
{id:"email",name:"EMAIL",category:"red",description:"Direct professional contact.",content:["isaacadigunoluwole@gmail.com"],tags:["email","contact"]},
{id:"github",name:"GITHUB",category:"red",description:"Code, experiments and public repositories.",tags:["repositories","code"],links:[{label:"github.com/HephzibahBehulah",url:"https://github.com/HephzibahBehulah"}]},
{id:"linkedin",name:"LINKEDIN",category:"red",description:"Professional profile.",tags:["professional"],links:[{label:"linkedin.com/in/isaacoluwoleadigun",url:"https://www.linkedin.com/in/isaacoluwoleadigun"}]},
{id:"blog",name:"BLOG",category:"red",description:"Cybersecurity and technology writing.",tags:["articles","education"],links:[{label:"hephzibahbehulah.blogspot.com",url:"https://hephzibahbehulah.blogspot.com/"}]},
{id:"gitbook",name:"GITBOOK",category:"red",description:"Technical notes and learning documentation.",tags:["documentation","learning"],links:[{label:"Open GitBook",url:"https://app.gitbook.com/invite/8uMbyzwWNsEhLYW0DgiG/6UHlnP4vlkPnzDmzuxw5"}]},
{id:"x",name:"X",category:"red",description:"Public social channel.",links:[{label:"X / @HephzibahBehulah",url:"https://x.com/HephzibahBehulah"}]},
{id:"facebook",name:"FACEBOOK",category:"red",description:"Public social channel.",links:[{label:"Facebook / HephzibahBehulah",url:"https://facebook.com/HephzibahBehulah"}]},
{id:"tiktok",name:"TIKTOK",category:"red",description:"Public social channel.",links:[{label:"TikTok / @hephzibahbehulah",url:"https://tiktok.com/@hephzibahbehulah"}]},
{id:"youtube",name:"YOUTUBE",category:"red",description:"Public video channel.",links:[{label:"YouTube / @hephzibahbehulah",url:"https://youtube.com/@hephzibahbehulah"}]},
{id:"newsletter",name:"NEWSLETTER",category:"red",description:"GDPR-conscious newsletter signup.",content:["The site can collect newsletter subscriptions only through an explicit consent flow. No hidden tracking or pre-checked consent is intended."],tags:["GDPR","consent","newsletter"]}
]}
]};